In [8]:
# 1
import numpy as np

A = np.array([[2, 4, 0], [-3, 1, -1], [0, 3, 2]])
B = np.array([[3, -1, 2], [-2, -3, 0], [1, 0, -2]])
C = np.dot(A, B)
print C

[[ -2 -14   4]
 [-12   0  -4]
 [ -4  -9  -4]]


In [9]:
# 2
def makeArrayPositive(myArray):
    myArray[myArray<0] = 0
    
makeArrayPositive(C)
print C

[[0 0 4]
 [0 0 0]
 [0 0 0]]


In [13]:
# 3
# What does it return??
def problem3(n):
    A = np.random.rand(n, n)
    meanArray = A.mean(axis=0)
    variance = meanArray.var()
    print A
    print meanArray
    print variance

In [2]:
import numpy as np

def laplace(myArray, tolerance):
    myArrayCopy = np.copy(myArray)
    arrayDiff = tolerance
    while arrayDiff >= tolerance:
        myArrayCopy[1:-1, 1:-1] = (myArrayCopy[:-2, 1:-1] + myArrayCopy[1:-1, 2:]) / 4.0
        myArray = myArrayCopy - myArray
        myArray = np.absolute(myArray)
        arrayDiff = myArray.max()
        myArray = myArrayCopy
        
from matplotlib import pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
n = 100
tol = .0001
U = np.ones ((n, n))
U [:,0] = 100 # sets west boundary condition
U [:,-1] = 100 # sets east boundary condition
U [0] = 0 # sets north boundary condition
U [-1] = 0 # sets south boundary condition
# U has been changed in place (note that laplace is the name of
# the function in this case).
laplace(U, tol)
x = np.linspace(0, 1, n)
y = np.linspace(0, 1, n)
X, Y = np.meshgrid(x, y)
fig = plt.figure()
ax = fig.gca(projection = '3d')
ax.plot_surface (X, Y, U, rstride=5)
plt.show()

In [4]:
import numpy as np

myArray = np.random.randint(255, size=(100, 100, 3))
def blue_shift(myArray):
    mult = np.array([.5, .5, 1.0])
    mult.reshape(3, 1, 1)
    return myArray * mult

blue_shift(myArray)
    
original, blue = blue_shift()
original = 255 - original
blue = 255 - blue
plt.subplot(1,2,1)
plt.imshow(original)
plt.subplot(1,2,2)
plt.imshow(blue)
plt.show()

'\noriginal, blue = blue_shift()\noriginal = 255 - original\nblue = 255 - blue\nplt.subplot(1,2,1)\nplt.imshow(original)\nplt.subplot(1,2,2)\nplt.imshow(blue)\nplt.show()\n'